### ISSUE TITLE
elm makecmd

### ISSUE THREAD

**Issue by Parasrah** [Parasrah/kak-config#8]

**Comment by Parasrah** [comment]
this isn't done because it's a huge PITA due to the format of Elm's errors

**Comment by Parasrah** [comment]
need to go from something like:

```
ERROR in ./src/Main.elm
Module build failed (from ./node_modules/elm-webpack-loader/index.js):
Error: Compiler process exited with error Compilation failed
Compiling ...-- NAMING ERROR ---------------------------------------------------- src/Api.elm

I cannot find a `Context.mode` variable:

140|     case Context.mode context of
              ^^^^^^^^^^^^
The `Context` module does not expose a `mode` variable. These names seem close
though:

    Context.init
    Context.update
    context
    Context.modeMirror

Hint: Read <https://elm-lang.org/0.19.1/imports> to see how `import`
declarations work in Elm.

-- NAMING ERROR ---------------------------------------------------- src/Api.elm

I cannot find a `Context.coreAuthority` variable:

135|     Url.Builder.crossOrigin (toScheme context ++ "://" ++ Context.coreAuthority context) paths queryParams
                                                               ^^^^^^^^^^^^^^^^^^^^^
The `Context` module does not expose a `coreAuthority` variable. These names
seem close though:

    Context.coreAuthorityMirror
    Context.modeMirror
    Context.recordHistory
    Context.timeoutMirror

Hint: Read <https://elm-lang.org/0.19.1/imports> to see how `import`
declarations work in Elm.

-- NAMING ERROR ---------------------------------------------------- src/Api.elm

I cannot find a `Context.timeout` variable:

129|         , timeout = Context.timeout context |> toFloat |> Just
                         ^^^^^^^^^^^^^^^
The `Context` module does not expose a `timeout` variable. These names seem
close though:

    Context.init
    Context.timeoutMirror
    Context.mapRecord
    Context.pushUrl

Hint: Read <https://elm-lang.org/0.19.1/imports> to see how `import`
declarations work in Elm.

-- NAMING ERROR ---------------------------------------------------- src/Api.elm

I cannot find a `Context.timeout` variable:

117|         , timeout = Context.timeout context |> toFloat |> Just
                         ^^^^^^^^^^^^^^^
The `Context` module does not expose a `timeout` variable. These names seem
close though:

    Context.init
    Context.timeoutMirror
    Context.mapRecord
    Context.pushUrl

Hint: Read <https://elm-lang.org/0.19.1/imports> to see how `import`
declarations work in Elm.

-- NAMING ERROR ---------------------------------------------------- src/Api.elm

I cannot find a `Context.retries` variable:

67|     withRetriesInner (Context.retries context) (Task.mapError NotEmptyList.singleton task)
                          ^^^^^^^^^^^^^^^
The `Context` module does not expose a `retries` variable. These names seem
close though:

    Context.routeLens
    Context.init
    Context.retriesMirror
    Context.update

Hint: Read <https://elm-lang.org/0.19.1/imports> to see how `import`
declarations work in Elm.

                                                                      Api  ↑    
====o======================================================================o====
    ↓  View.Header


-- NAMING ERROR -------------------------------------------- src/View/Header.elm

I cannot find a `Context.device` variable:

14|             |> Context.device
                   ^^^^^^^^^^^^^^
The `Context` module does not expose a `device` variable. These names seem close
though:

    Context.deviceLens
    Context.init
    Context.update
    Context.keyMirror

Hint: Read <https://elm-lang.org/0.19.1/imports> to see how `import`
declarations work in Elm.

Detected problems in 2 modules.

    at ChildProcess.<anonymous> (/home/parasrah/Projects/campground/spa/node_modules/node-elm-compiler/dist/index.js:131:35)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
 @ ./src/index.js 2:0-32 5:14-17
 @ multi ./src/index.js
```

to:

```
src/Api.elm:140:1: NAMING ERROR | case Context.mode context of
src/Api.elm:135:1: NAMING ERROR | Url.Builder.crossOrigin (toScheme context ++ "://" ++ Context.coreAuthority context) paths queryParams
src/Api.elm:129:1: NAMING ERROR | , timeout = Context.timeout context |> toFloat |> Just
src/Api.elm:117:1: NAMING ERROR | , timeout = Context.timeout context |> toFloat |> Just
src/Api.elm:67:1: NAMING ERROR | withRetriesInner (Context.retries context) (Task.mapError NotEmptyList.singleton task)
View/Header.elm:14:1: NAMING ERROR | |> Context.device

```

**Comment by Parasrah** [comment]
It was actually pretty trivial to accomplish this transformation with kakoune itself. I wonder if it would be possible to pipe the output into a new instance of kakoune (loaded without any config so it's fast), apply the same operations I did, and output the result?

**Comment by Parasrah** [comment]
Thanks to some help on the kakoune repo I learned there is indeed a way to do this already in kakoune using the `-f` flag, and this has now been completed
